title: GUO

baseurl:
sass:
    style: compressed

exclude:
- README.md

include:
- _pages

#Jekyll-Photo-Gallery Settings
exiftag:
 sources:
   - images/photography #Set to location of photos
#https://github.com/zroger/jekyll-minimagick
mini_magick:
    photography:
        source: images/photography
        destination: images/photography/thumbnails
        resize: "1280x720"
    headers:
        source: images/headers
        destination: images/headers/thumbnails
        resize: "400x250"
